## Libraries

In [5]:
#Import libraries
import pandas as pd
import numpy as np

## Q1. Pandas version

In [8]:
#Check pandas version
pd.__version__

'2.2.2'

## Get the data

In [14]:
#Load data in dataframe
df = pd.read_csv('laptops.csv')
df.head(1)

Laptop Status Brand       Model  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New  Asus  ExpertBook   

             CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
0  Intel Core i5    8      512          SSD  NaN    15.6    No       1009.0

## Q2. Records count

In [17]:
#Check number of records
len(df)

2160

## Q3. Laptop brands

In [28]:
#Count unique laptop brands
df['Brand'].nunique()

27

## Q4. Missing values

In [75]:
#Check for missing values
(df.isnull().sum() >=1).sum()

3

## Q5. Maximum final price

In [146]:
# Filter df to Dell brand
dell_df = df[df['Brand'] == 'Dell']
#dell_df
#Max price
max_final_price = dell_df['Final Price'].max()
max_final_price

3936.0

## Q6. Median value of Screen

In [249]:
#Median Value
median = df['Screen'].median()
print(median)
#Most Frequent Value
mode = df['Screen'].mode().iloc[0]
print(mode)

15.6
15.6


In [259]:
#Fill nas
df1 = df.fillna({'Screen' : mode})
df1
#Updated Median
upd_median = df1['Screen'].median()
print(upd_median)

15.6


In [432]:
#Chech if updated median is not equal to median (originally calculated)
median != upd_median

False

## Q7. Sum of Weights

In [274]:
# Filter df to Innjoo brand
innjoo_df = df[df['Brand'] == 'Innjoo']
new_df = innjoo_df[['RAM','Storage','Screen']]
new_df

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [300]:
#Get underlying NumPy array
X = new_df.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [302]:
#Traspose X
Xt = X.T
Xt

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [384]:
#Matrix-matrix multiplication between the transpose of X and X
XTX = Xt.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [390]:
#Check shape
XTX.shape

(3, 3)

In [392]:
#Compute Inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [394]:
#Create y array
y = np.array(
    [1100,1300,800,900,1000,1100]
)
y

array([1100, 1300,  800,  900, 1000, 1100])

In [396]:
#Check shape
y.shape

(6,)

In [418]:
#Multiply XTX_inv * Xt * y
w = XTX_inv.dot(Xt).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [428]:
#Sum array & round to two decimals
Sum = np.sum(w)
Sum.round(2)

91.3